server:
  applicationConnectors:
  - type: http 
    port: 9080
  adminConnectors:
  - type: http
    port: 9081

logging:
  level: INFO
  loggers:
    org.nil: DEBUG

swagger:
  resourcePackage: org.nil.beanValidation.resources